<?php View::content() ?>
<!-- Button trigger modal -->
<script src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.0.2/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.0.2/js/responsive.bootstrap.min.js"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.0.2/css/responsive.bootstrap.min.css">
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Subir archivo
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Subir Archivo</h4>
      </div>
      <div class="modal-body">
       	<?php echo Form::openMultipart() ?>
		    <p>
		    	<?php Flash::info('Ingrese un archivo .zip, .rar ó .xls:') ?>
		    </p>
		    <div class="form-group">
		    	<label for="">Nombre archivo</label>
		    	<input type="text" class="form-control" name="nombre">
		    </div>
		    <?php echo Form::hidden("usuarios_id",NULL,$usuario->id) ?>
		    <?php echo Form::file('archivo') ?>
		    <?php echo Form::hidden('oculto', NULL, '1') //para saber si se envió el form ?>
		    
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="return false;">Cerrar</button>
       
        <?php echo Form::submit('subir','class="btn btn-primary"') ?>
		<?php echo Form::close() ?>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<table class="table">
	<thead>
		<th>#</th>
		<th>Archivo</th>
		<th></th>
	</thead>
	<?php if (empty($archivos)): ?>
		<tr>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		
	<?php else: ?>
		<?php $count=1 ?>
		<?php foreach ($archivos as $key => $value): ?>
			
			<tr>
				<td><?php echo $count ?></td>
				<td><?php echo $value->nombre ?></td>
				<td><a href="<?php echo PUBLIC_PATH.'archivo/descargar/'.$value->id ?>" title="DESCARGAR"><span class='glyphicon glyphicon-download-alt'></span></a></td>
			</tr>
			<?php $count++; ?>
		<?php endforeach ?>
	<?php endif ?>
</table>
<script type="text/javascript">
	$(document).ready(function(){
	    $('.table').DataTable({
	    	language:{
			    "sProcessing":     "Procesando...",
			    "sLengthMenu":     "Mostrar _MENU_ registros",
			    "sZeroRecords":    "No se encontraron resultados",
			    "sEmptyTable":     "Ningún dato disponible en esta tabla",
			    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
			    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
			    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
			    "sInfoPostFix":    "",
			    "sSearch":         "Buscar:",
			    "sUrl":            "",
			    "sInfoThousands":  ",",
			    "sLoadingRecords": "Cargando...",
			    "oPaginate": {
			        "sFirst":    "Primero",
			        "sLast":     "Último",
			        "sNext":     "Siguiente",
			        "sPrevious": "Anterior"
			    },
			    "oAria": {
			        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
			        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
			    }
			}
	    });
	   
	});
</script>
