<?php View::content() ?>
<?php echo Tag::css("form_create") ?>

  
<div class="col-md-6">
<form class="form-horizontal" method="post" action="<?php echo PUBLIC_PATH.'usuarios/create' ?>">

<!--                     <div class="form-group">
        <label for="name" class="cols-sm-2 control-label">Your Name</label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="name" id="name"  placeholder="Enter your Name"/>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label for="email" class="cols-sm-2 control-label">Your Email</label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="email" id="email"  placeholder="Enter your Email"/>
            </div>
        </div>
    </div> -->

    <div class="form-group">
        <label for="username" class="cols-sm-2 control-label">Nombre de Usuario</label>
        <div class="cols-sm-6">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
                <?php echo Form::text("usuarios.username","class='form-control' id='username' placeholder='Introduce el Nombre de Usuario' required='required'") ?>
              
            </div>
        </div>
    </div>

    <div class="form-group">
        <label for="password" class="cols-sm-2 control-label">Contraseña</label>
        <div class="cols-sm-6">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                <?php echo Form::pass("usuarios.password","class='form-control' id='password' placeholder='Introduce la Contraseña' required='required'") ?>
                
            </div>
        </div>
    </div>

    <div class="form-group">
        <label for="confirm" class="cols-sm-2 control-label">Confirmar Contraseña</label>
        <div class="cols-sm-6">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                <?php echo Form::pass("usuarios.confirm","class='form-control' id='confirm' placeholder='Confirmar Contraseña' required='required'") ?>
          
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="confirm" class="cols-sm-2 control-label">Rol de Usuario</label>
        <div class="cols-sm-6">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                <?php echo Form::select("usuarios.rol",array(""=>"Seleccione Uno","A"=>"Administrador","U"=>"Usuario"),"class='form-control' id='rol' required='required'") ?>
          
            </div>
        </div>
    </div>

    <div class="form-group ">
        <button type="submit" class="btn btn-primary  login-button">Crear usuario</button>
    </div>
    <!-- <div class="login-register">
        <a href="index.php">Registro</a>
    </div> -->
</form>
          </div>
