<br>
<div class="container well">
	<div class="page_header">
	<center>
		<div class="row">
			<div class="col-md-6"><h1>Términos y Condiciones</h1></div>
			<div class="col-md-6"><?php echo Html::img("logo_company.png","ExpoEmpledo","style='width:200px'") ?></div>
		</div>
	</center>

	</div>

	<p class=MsoNormal align=center style='text-align:center'><b><span lang=ES-MX
style='font-family:Arial'>T&eacute;rminos y Condiciones de Uso del Sitio Web </span></b><span
lang=ES-MX style='font-family:Arial'><b>Expoempleo.com</b></span></p>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=ES-MX
style='font-size:14.0pt;font-family:Arial'>&nbsp;</span></b></p>

<p class=MsoNormal style='text-align:justify'><span lang=ES-MX
style='font-family:Arial'>Los siguientes t&eacute;rminos y condiciones (los "T&eacute;rminos
y Condiciones") rigen el uso que usted le d&eacute; a este sitio web y a cualquiera de
los contenidos disponibles por o a trav&eacute;s de este sitio web, incluyendo
cualquier contenido derivado del mismo (el "Sitio Web"). Time Inc. ("Time Inc."
o "nosotros") ha puesto a su disposici&oacute;n el Sitio Web. Podemos cambiar los
T&eacute;rminos y Condiciones de vez en cuando, en cualquier momento sin ninguna
notificaci&oacute;n, s&oacute;lo publicando los cambios en el Sitio Web. AL USAR EL SITIO
WEB, USTED ACEPTA Y EST&Eacute; DE ACUERDO CON ESTOS T&Eacute;RMINOS Y CONDICIONES EN LO QUE
SE REFIERE A SU USO DEL SITIO WEB. Si usted no est&aacute; de acuerdo con estos
T&eacute;rminos y Condiciones, no puede tener acceso al mismo ni usar el Sitio Web de
ninguna otra manera.</span></p>

<p class=MsoNormal style='text-align:justify'><span lang=ES-MX
style='font-family:Arial'>&nbsp;</span></p>

<p class=MsoNormal style='text-align:justify'><span lang=ES-MX
style='font-family:Arial'>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u>Derechos de Propiedad. </u>Entre usted
y Time Inc., Time Inc. es due&ntilde;o &uacute;nico y exclusivo, de todos los derechos,
t&iacute;tulo e intereses en y del Sitio Web, de todo el contenido (incluyendo, por
ejemplo, audio, fotograf&iacute;as, ilustraciones, gr&aacute;ficos, otros medios visuales,
videos, copias, textos, software, t&iacute;tulos, archivos de Onda de choque, etc.),
c&oacute;digos, datos y materiales del mismo, el aspecto y el ambiente, el dise&ntilde;o y la
organizaci&oacute;n del Sitio Web y la compilaci&oacute;n de los contenidos, c&oacute;digos, datos y
los materiales en el Sitio Web, incluyendo pero no limitado a, cualesquiera
derechos de autor, derechos de marca, derechos de patente, derechos de base de
datos, derechos morales, derechos sui generis y otras propiedades intelectuales
y derechos patrimoniales del mismo. Su uso del Sitio Web no le otorga propiedad
de ninguno de los contenidos, c&oacute;digos, datos o materiales a los que pueda acceder
en o a trav&eacute;s del Sitio Web. </span></p>

<center>
<div class="row">
	<?php echo Form::open('usuarios/dashboard') ?>
	<div class="col-md-6">
		<button class="btn btn-danger btn-lg" name="terminos" value="no_acepto">No Acepto</button>
	</div>
	<div class="col-md-6">
		<button class="btn btn-success btn-lg" name="terminos" value="acepto">Acepto</button>
	</div>
	<?php echo Form::close() ?>
</div>
</center>
</div>
<style type="text/css">
	
	body, html{
     height: 100%;
 	background-repeat: no-repeat;
 	background-color: #d3d3d3;
 	font-family: 'Oxygen', sans-serif;
}

</style>