<?php echo Tag::css("form_login") ?>
<div class="container">
        <div class="row main">
            <div class="panel-heading">
                 <div class="panel-title text-center">
                    <?php echo Html::img("logo_company.png","Compañia","class='logo_company'") ?>
                    <h1 class="title"></h1>
                    <hr />
                    <?php View::content() ?>
                </div>
            </div> 
        <div class="main-login main-center">
                <form class="form-horizontal" method="post" action="<?php echo PUBLIC_PATH ?>">

<!--                     <div class="form-group">
                        <label for="name" class="cols-sm-2 control-label">Your Name</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                                <input type="text" class="form-control" name="name" id="name"  placeholder="Enter your Name"/>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email" class="cols-sm-2 control-label">Your Email</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                                <input type="text" class="form-control" name="email" id="email"  placeholder="Enter your Email"/>
                            </div>
                        </div>
                    </div> -->

                    <div class="form-group">
                        <label for="username" class="cols-sm-2 control-label">Nombre de Usuario</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
                                <input type="text" class="form-control" name="username" id="username"  placeholder="Introduce el Nombre de Usuario"/>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="password" class="cols-sm-2 control-label">Contraseña</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                                <input type="password" class="form-control" name="password" id="password"  placeholder="Introduce la Contraseña"/>
                            </div>
                        </div>
                    </div>

<!--                     <div class="form-group">
                        <label for="confirm" class="cols-sm-2 control-label">Confirm Password</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                                <input type="password" class="form-control" name="confirm" id="confirm"  placeholder="Confirm your Password"/>
                            </div>
                        </div>
                    </div> -->

                    <div class="form-group ">
                        <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Iniciar Sesión</button>
                    </div>
                    <!-- <div class="login-register">
                        <a href="index.php">Registro</a>
                    </div> -->
                </form>
            </div>
    </div>
</div>