<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <!-- http://www.bootply.com/WWaNzfHP5q -->
  <title>
  <?php if (isset($titulo)): ?>
    <?php echo $titulo; ?>
  <?php else: ?>
    Cartera de trabajadores
  <?php endif ?>
  </title>
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH.'bootstrap/css/bootstrap.css' ?>">
  <?php echo Tag::css('dash') ?>
  <?php echo Html::includeCss() ?>
  <?php echo Tag::js('jquery/jquery.min') ?>
  <script type="text/javascript" src="<?php echo PUBLIC_PATH.'bootstrap/js/bootstrap.js' ?>"></script>
</head>
<body>
<!-- Header -->
<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <?php echo Html::img("logo_company.png","ExpoEmpleo Logo","class='logo_company_dash'") ?>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
      </button>
      <span class="navbar-brand" href="#"></span>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
            <i class="glyphicon glyphicon-user"></i> <?php echo ucfirst(Auth::get('username')) ?> <span class="caret"></span></a>
          <ul id="g-account-menu" class="dropdown-menu" role="menu">
            <li><a href="#">Mis Opciones</a></li>
            <li><a href="<?php echo PUBLIC_PATH.'usuarios/logout' ?>"><i class="glyphicon glyphicon-lock"></i> Cerrar Sesión</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div><!-- /container -->
</div>
<!-- /Header -->

<!-- Main -->
<div class="container">
  
  <!-- upper section -->
  <div class="row">
  <div class="col-sm-3">
      <!-- left -->
      <h3><i class="glyphicon glyphicon-briefcase"></i> Opciones</h3>
      <hr>
      
      <ul class="nav nav-stacked">
        <?php if (Auth::get('rol') == "A"): ?>        
          <li><a href="<?php echo PUBLIC_PATH.'usuarios/create' ?>" ><i class="glyphicon glyphicon-link"></i> Crear Usuario</a></li>
          <li><a href="<?php echo PUBLIC_PATH.'usuarios/' ?>" ><i class="glyphicon glyphicon-list-alt"></i> Lista de Usuarios</a></li>
          <!-- <li><a href="http://www.bootply.com/85861" target="ext"><i class="glyphicon glyphicon-briefcase"></i> Asignar Base de datos</a></li> -->
        <?php else: ?>

          <li><a href="<?php echo PUBLIC_PATH.'usuarios/mis_archivos' ?>"><i class="glyphicon glyphicon-book"></i> Mis Archivos</a></li>
        <?php endif ?>
          <!-- <li><a href="http://www.bootply.com/85861" target="ext"><i class="glyphicon glyphicon-flash"></i> Alerts</a></li>
          <li><a href="http://www.bootply.com/85861" target="ext"><i class="glyphicon glyphicon-list-alt"></i> Reports</a></li>
          <li><a href="http://www.bootply.com/85861" target="ext"><i class="glyphicon glyphicon-time"></i> Real-time</a></li>
          <li><a href="http://www.bootply.com/85861" target="ext"><i class="glyphicon glyphicon-plus"></i> Advanced..</a></li> -->
      </ul>
      
      <hr>
      
    </div><!-- /span-3 -->
    <div class="col-sm-9">
        
      <!-- column 2 --> 
       <h3><i class="glyphicon glyphicon-dashboard"></i> 
        <?php if (isset($titulo)): ?>
          <?php echo $titulo; ?>
        <?php else: ?>
          Cartera de trabajadores
        <?php endif ?>
       </h3>  
            
       <hr>
      
      <div class="row">
        <?php echo View::content() ?>
      </div>
    </div><!--/col-span-9-->
    
  </div><!--/row-->
  <!-- /upper section -->
  
  <!-- lower section -->
  
  
</div><!--/container-->
<!-- /Main -->


<footer class="text-center"><?php echo Html::img('logo_company.png',"ExpoEmpleo LOGO","class='logo_company_dash'") ?></footer>


<div class="modal" id="addWidgetModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Add Widget</h4>
      </div>
      <div class="modal-body">
        <p>Add a widget stuff here..</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn">Close</a>
        <a href="#" class="btn btn-primary">Save changes</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dalog -->
</div><!-- /.modal -->



  
</body>
</html>
